<a href="https://colab.research.google.com/github/saad-ameer/Python-for-Data-Analyst/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python Notes – NumPy Introduction

### * What is NumPy?

* NumPy stands for Numerical Python.
* Used for working with numerical data and multi-dimensional arrays.
* Arrays are more memory-efficient and faster than Python lists.
* All elements in a NumPy array must be of the same data type (homogeneous).

---

### * 1D Array Creation

* Import NumPy using alias:
  * `import numpy as np`
* Convert a list to NumPy array:
  * `arr = np.array([1, 2, 3, 4, 5])`
* Check type: `type(arr)` → `numpy.ndarray`
* Check shape: `arr.shape` → returns a tuple (length, )

---

### * 2D Array Creation

* Use list of lists:
  * `arr2d = np.array([[1, 2], [3, 4], [5, 6]])`
* Shape: `arr2d.shape` → `(3, 2)` (3 rows, 2 columns)

---

### * Acceptable Inputs

* You can pass:
  * Lists → creates normal array
  * Tuples → creates array
  * Sets → will be treated as single element unless converted to list

---

### * Data Types in NumPy

* Data type can be set using `dtype` parameter:
  * `np.array([1, 2, 3], dtype=np.longdouble)`
* You can also use character codes, e.g., `'g'` for long double
* Useful for higher precision, e.g.:
  * `np.longdouble(100) / np.longdouble(3)` gives more precise result

---

### * Summary

* NumPy arrays:
  * Are faster and more efficient than lists
  * Have fixed type and shape
* Use `.shape` to check dimensions
* Use `dtype` to control data precision
* Essential for later data libraries like pandas

In [43]:
import numpy as np

In [44]:
list1 = [2,3,4,6,22,6,7]

In [45]:
x = np.array(list1)

In [46]:
type(x)

numpy.ndarray

In [47]:
np.shape(x)

(7,)

In [48]:
x.shape

(7,)

In [49]:
np.array([5,3,78,2,378,51,2])

array([  5,   3,  78,   2, 378,  51,   2])

In [50]:
np.array((2,4,6,2,2,6,6,6,5))

array([2, 4, 6, 2, 2, 6, 6, 6, 5])

In [51]:
np.array({2,5,6,3,4,6,2,2})

array({2, 3, 4, 5, 6}, dtype=object)

In [52]:
np.array({2,5,6,3,4,6,2,2}).shape

()

In [53]:
arr2d = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])

In [54]:
arr2d

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [55]:
arr2d.shape

(3, 4)

In [56]:
list1

[2, 3, 4, 6, 22, 6, 7]

In [57]:
list2 = [1,34,45,6,7,3,3]

In [58]:
arr2d_2 = np.array([list1,list2])

In [59]:
arr2d_2

array([[ 2,  3,  4,  6, 22,  6,  7],
       [ 1, 34, 45,  6,  7,  3,  3]])

In [60]:
arr2d_2.shape

(2, 7)

In [61]:
100/3

33.333333333333336

In [62]:
np.longdouble(100)/np.longdouble(3)

np.longdouble('33.333333333333333332')

In [63]:
np.array([1,2,34,56,5,3.1453,6])

array([ 1.    ,  2.    , 34.    , 56.    ,  5.    ,  3.1453,  6.    ])

In [64]:
np.array([1,2,34,56,5,3.145,6],dtype='longdouble')

array([ 1.   ,  2.   , 34.   , 56.   ,  5.   ,  3.145,  6.   ],
      dtype=float128)

In [65]:
np.array([1,2,34,56,5,3.145,6],dtype='g')

array([ 1.   ,  2.   , 34.   , 56.   ,  5.   ,  3.145,  6.   ],
      dtype=float128)

## Python Notes – NumPy Indexing & Slicing

### * 1D vs 2D Arrays

* 1D array: `arr1 = np.array([1, 2, 3, 4])`
* 2D array (matrix): `arr2 = np.array([[1, 2, 3, 4]])` (note the nested list)
* Use `.shape` to confirm dimensions  
  * 1D → `(4,)`  
  * 2D → `(1, 4)`

---

### * Indexing & Slicing – 1D Arrays

* `arr[4]` → 5th element (indexing starts at 0)
* `arr[4:]` → From 5th element to end
* `arr[2:6]` → From index 2 to 5
* `arr[::-1]` → Reverse the array

---

### * Indexing & Slicing – 2D Arrays

* General format: `arr[row_slice, col_slice]`
* Example:  
  * `arr[1:, 2:]` → From row 1 to end, column 2 to end  
  * `arr[2, 6]` → Element at 3rd row, 7th column  
  * `arr[::-1, :]` → Flip rows (zero axis)  
  * `arr[:, ::-1]` → Flip columns (one axis)

---

### * Boolean Indexing

* Works on both 1D and 2D arrays  
* Example for 1D:  
  * `arr > 3` → Boolean array  
  * `arr[arr > 3]` → Values > 3  
* Example for 2D:  
  * `arr[arr > 10]` → Flattens and filters values > 10

---

### * Reassignment in Arrays vs Lists

* Lists: Only individual elements can be reassigned  
  * `list[0] = 10` → Works  
  * `list[:] = 10` → Error
* Arrays: Can reassign multiple elements  
  * `arr[:] = 10` → Works

---

### * Summary

* Use slicing for extracting subarrays or flipping rows/columns  
* Boolean indexing filters values based on conditions  
* Arrays support vectorized reassignment, lists don’t

In [66]:
import numpy as np

In [67]:
arr1 = np.array([1,1,1,1])

In [68]:
arr2 = np.array([[2,2,2,2]])

In [69]:
arr1.shape

(4,)

In [70]:
arr2.shape

(1, 4)

In [71]:
array_1d = np.array([2,4,7,74,2,2,24,6])
array_2d = np.array([[2,4,7,74,2,2,24,6],[5,3,2,25,5,2,1,4],[1,4,5,3,3,4,5,1]])

In [72]:
array_1d

array([ 2,  4,  7, 74,  2,  2, 24,  6])

In [73]:
array_2d

array([[ 2,  4,  7, 74,  2,  2, 24,  6],
       [ 5,  3,  2, 25,  5,  2,  1,  4],
       [ 1,  4,  5,  3,  3,  4,  5,  1]])

In [74]:
array_1d[6]

np.int64(24)

In [75]:
array_1d[5:]

array([ 2, 24,  6])

In [76]:
array_1d[2:6]

array([ 7, 74,  2,  2])

In [77]:
array_1d[::-1]

array([ 6, 24,  2,  2, 74,  7,  4,  2])

In [80]:
array_2d[1:,2:]

array([[ 2, 25,  5,  2,  1,  4],
       [ 5,  3,  3,  4,  5,  1]])

In [81]:
array_2d[2:,1:]

array([[4, 5, 3, 3, 4, 5, 1]])

In [86]:
array_2d[:,5:]

array([[ 2, 24,  6],
       [ 2,  1,  4],
       [ 4,  5,  1]])

In [92]:
array_2d[2,6]

np.int64(5)

In [93]:
array_2d

array([[ 2,  4,  7, 74,  2,  2, 24,  6],
       [ 5,  3,  2, 25,  5,  2,  1,  4],
       [ 1,  4,  5,  3,  3,  4,  5,  1]])

In [94]:
array_2d[::-1,]

array([[ 1,  4,  5,  3,  3,  4,  5,  1],
       [ 5,  3,  2, 25,  5,  2,  1,  4],
       [ 2,  4,  7, 74,  2,  2, 24,  6]])

In [96]:
array_2d[:,::-1]

array([[ 6, 24,  2,  2, 74,  7,  4,  2],
       [ 4,  1,  2,  5, 25,  2,  3,  5],
       [ 1,  5,  4,  3,  3,  5,  4,  1]])

In [100]:
array_2d[::-1,::-1]

array([[ 1,  5,  4,  3,  3,  5,  4,  1],
       [ 4,  1,  2,  5, 25,  2,  3,  5],
       [ 6, 24,  2,  2, 74,  7,  4,  2]])

In [101]:
array_1d

array([ 2,  4,  7, 74,  2,  2, 24,  6])

In [102]:
array_1d>4

array([False, False,  True,  True, False, False,  True,  True])

In [103]:
array_1d[array_1d>4]

array([ 7, 74, 24,  6])

In [104]:
array_2d

array([[ 2,  4,  7, 74,  2,  2, 24,  6],
       [ 5,  3,  2, 25,  5,  2,  1,  4],
       [ 1,  4,  5,  3,  3,  4,  5,  1]])

In [106]:
array_2d>12

array([[False, False, False,  True, False, False,  True, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [107]:
array_2d[array_2d>12]

array([74, 24, 25])

In [108]:
array_2d[array_2d>12].shape

(3,)

In [109]:
array_1 = np.array([1,2,34,34,4])

In [110]:
list_1 = [12,4,5,6,3]

In [111]:
list_1[2] = 12

In [112]:
list_1

[12, 4, 12, 6, 3]

In [114]:
#list_1[:] = 4

In [115]:
array_1[:] = 4

In [116]:
array_1

array([4, 4, 4, 4, 4])

## NumPy Notes – Array Manipulation & Useful Functions

### * Creating Arrays
* Use `np.array()` to create 1D or 2D arrays
* Example: `np.array([1, 2, 3])` or `np.array([[1, 2], [3, 4]])`

---

### * Reshape Arrays
* Use `np.reshape(array, (rows, cols))` or `array.reshape(rows, cols)`
* Reshape only works if total number of elements matches
* Example:
  * `np.reshape(arr, (2, 5))` converts a 1D array of 10 elements to 2x5

---

### * Flatten Arrays
* Converts any array to 1D
* `np.flatten(array)` or `array.ravel()` or `np.ravel(array)`
* Example:
  * `np.ravel(arr)` → 1D view of the array

---

### * Concatenate Arrays
* Use `np.concatenate((arr1, arr2), axis=0 or 1)`
* Axis 0 = row-wise (requires same number of columns)  
* Axis 1 = column-wise (requires same number of rows)
* Example:
  * `np.concatenate((arr1, arr2), axis=0)`

---

### * Transpose Arrays
* Invert rows and columns using `array.T` or `np.transpose(array)`
* Example:  
  * `array.T` swaps rows with columns in 2D array

---

### * Sort Arrays
* Use `np.sort(array, axis=0 or 1)`
* Axis 0 → sort each column  
* Axis 1 → sort each row
* Example:
  * `np.sort(arr, axis=1)` sorts each row in ascending order

---

### * Notes
* `reshape` and `sort` can also be used as methods: `array.reshape()` and `array.sort()`
* Reshape doesn’t change the original array unless reassigned
* Flattening turns a 2D array into 1D without copying data (`ravel` is a view)

In [117]:
import numpy as np

In [137]:
array_1 = np.array([1,2,3,3,4,3,4,5,43,6,2,3])

In [119]:
array_2 = np.array([[2,34,4,2,1],[12,4,1,1,3]])

In [120]:
array_1.shape

(14,)

In [121]:
array_2.shape

(2, 5)

In [138]:
np.reshape(array_1,(2,6))

array([[ 1,  2,  3,  3,  4,  3],
       [ 4,  5, 43,  6,  2,  3]])

In [139]:
array_1.reshape(3,4)

array([[ 1,  2,  3,  3],
       [ 4,  3,  4,  5],
       [43,  6,  2,  3]])

In [140]:
array_1.reshape(4,3)

array([[ 1,  2,  3],
       [ 3,  4,  3],
       [ 4,  5, 43],
       [ 6,  2,  3]])

In [141]:
array_1.reshape(6,2)

array([[ 1,  2],
       [ 3,  3],
       [ 4,  3],
       [ 4,  5],
       [43,  6],
       [ 2,  3]])

In [142]:
array_2

array([[ 2, 34,  4,  2,  1],
       [12,  4,  1,  1,  3]])

In [143]:
np.ndarray.flatten(array_2)

array([ 2, 34,  4,  2,  1, 12,  4,  1,  1,  3])

In [145]:
np.ndarray.flatten(array_2).shape

(10,)

In [146]:
np.ravel(array_2)

array([ 2, 34,  4,  2,  1, 12,  4,  1,  1,  3])

In [152]:
array_1 = np.array([[1,1,1],[2,2,2]])

In [153]:
array_2 = np.array([[3,3,3],[4,4,4],[5,5,5]])

In [154]:
array_3 = np.array([[4,4],[5,5],[6,6]])

In [150]:
array_1

array([[1, 1, 1],
       [2, 2, 2]])

In [151]:
array_1.shape

(2, 3)

In [155]:
array_2

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [156]:
array_2.shape

(3, 3)

In [157]:
array_3

array([[4, 4],
       [5, 5],
       [6, 6]])

In [158]:
array_3.shape

(3, 2)

In [159]:
np.concatenate((array_1,array_2),axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [160]:
np.concatenate((array_3,array_2),axis=1)

array([[4, 4, 3, 3, 3],
       [5, 5, 4, 4, 4],
       [6, 6, 5, 5, 5]])

In [161]:
array_1

array([[1, 1, 1],
       [2, 2, 2]])

In [162]:
np.transpose(array_1)

array([[1, 2],
       [1, 2],
       [1, 2]])

In [164]:
array_1.transpose()

array([[1, 2],
       [1, 2],
       [1, 2]])

In [165]:
array_unsort = np.array([[10,50,20],[1,5,2]])

In [166]:
array_unsort

array([[10, 50, 20],
       [ 1,  5,  2]])

In [167]:
np.sort(array_unsort,axis=1)

array([[10, 20, 50],
       [ 1,  2,  5]])

In [168]:
np.sort(array_unsort,axis=0)

array([[ 1,  5,  2],
       [10, 50, 20]])

In [169]:
array_unsort

array([[10, 50, 20],
       [ 1,  5,  2]])

In [170]:
array_unsort.T

array([[10,  1],
       [50,  5],
       [20,  2]])

## NumPy Notes – Array Creation Functions

### * Create array with a fill value using `np.full()`

* Syntax: `np.full(shape, fill_value, dtype)`
* Example:  
  * `np.full((2, 5), 2)` → 2x5 matrix filled with 2  
  * `np.full((5, 5), 0, dtype='longdouble')` → 5x5 matrix of 0 with high precision

---

### * Create array with evenly spaced values using `np.arange()`

* Syntax: `np.arange(start, stop, step)`
* Stop is **exclusive**
* Example:  
  * `np.arange(0, 12, 2)` → array from 0 to 10 with step of 2  
  * Can be reshaped: `np.arange(0, 12, 2).reshape(2, 3)`

---

### * Create evenly spaced numbers over interval using `np.linspace()`

* Syntax: `np.linspace(start, stop, num)`
* Stop is **inclusive**
* Example:  
  * `np.linspace(0, 100, 25).reshape(5, 5)` → 5x5 matrix from 0 to 100

---

### * Create array with random values using `np.random.rand()`

* Syntax: `np.random.rand(rows, cols)`
* Returns values between 0 and 1
* Example:  
  * `np.random.rand(2, 5)` → 2x5 matrix with random floats from 0 to 1

---

### * Create array with random integers using `np.random.randint()`

* Syntax: `np.random.randint(low, high, size)`
* Returns random integers from `low` (inclusive) to `high` (exclusive)
* Example:  
  * `np.random.randint(-20, 20, (3, 3))` → 3x3 matrix with values from -20 to 19

---

### * Summary

* Use `np.full()` to create constant-value arrays  
* Use `np.arange()` for integer sequences with fixed step  
* Use `np.linspace()` for sequences with fixed number of values  
* Use `np.random.rand()` and `np.random.randint()` for random values  
* Arrays can be reshaped using `.reshape()`  
* Practice using `np.identity()`, `np.zeros()`, and `np.ones()` for further learning

In [171]:
import numpy as np

In [172]:
np.full((3,6),9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [173]:
np.full((5,7),fill_value=5,dtype=np.longdouble)

array([[5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.]], dtype=float128)

In [174]:
np.full(dtype=np.longdouble,shape=(5,5),fill_value=10)

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]], dtype=float128)

In [178]:
np.full((6,6),20,np.longdouble)

array([[20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20.]], dtype=float128)

In [185]:
np.arange(0,18,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [187]:
np.arange(0,18,2).reshape(3,3)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [188]:
np.arange(0,18,2).reshape(3,3).shape

(3, 3)

In [193]:
np.linspace(0,50,num=30)

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [199]:
np.linspace(0,50,num=30).reshape(10,3)

array([[ 0.        ,  1.72413793,  3.44827586],
       [ 5.17241379,  6.89655172,  8.62068966],
       [10.34482759, 12.06896552, 13.79310345],
       [15.51724138, 17.24137931, 18.96551724],
       [20.68965517, 22.4137931 , 24.13793103],
       [25.86206897, 27.5862069 , 29.31034483],
       [31.03448276, 32.75862069, 34.48275862],
       [36.20689655, 37.93103448, 39.65517241],
       [41.37931034, 43.10344828, 44.82758621],
       [46.55172414, 48.27586207, 50.        ]])

In [201]:
np.linspace(0,50,num=30).reshape(5,6)

array([[ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
         8.62068966],
       [10.34482759, 12.06896552, 13.79310345, 15.51724138, 17.24137931,
        18.96551724],
       [20.68965517, 22.4137931 , 24.13793103, 25.86206897, 27.5862069 ,
        29.31034483],
       [31.03448276, 32.75862069, 34.48275862, 36.20689655, 37.93103448,
        39.65517241],
       [41.37931034, 43.10344828, 44.82758621, 46.55172414, 48.27586207,
        50.        ]])

In [202]:
np.random.random((5,5))

array([[0.59536434, 0.68659915, 0.05022622, 0.01350301, 0.01322044],
       [0.0478648 , 0.54923599, 0.54009683, 0.63692739, 0.93673604],
       [0.64345938, 0.46174079, 0.59132718, 0.82158147, 0.54687981],
       [0.65661036, 0.26798634, 0.53740784, 0.22848866, 0.23892052],
       [0.94422639, 0.17164212, 0.83152314, 0.67955634, 0.97691097]])

In [206]:
np.random.rand(5,3)

array([[0.08988026, 0.33270171, 0.8032751 ],
       [0.94778205, 0.9164217 , 0.23285399],
       [0.38166609, 0.2706406 , 0.6228131 ],
       [0.3985176 , 0.57201181, 0.83846633],
       [0.74497341, 0.78059738, 0.38656438]])

In [218]:
np.random.randint(-10,10,(3,3))

array([[  6, -10,   6],
       [ -5,  -4,   3],
       [ -9,  -7,   1]])

In [219]:
np.random.randint(-30,30,(5,5))

array([[-21, -23, -20,  -8, -26],
       [-13, -24, -15,   7,  26],
       [-25,  -3,  21,  15, -12],
       [ -5,   9, -17,   6,  -3],
       [-12,   3,   1, -11,   5]])

In [226]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [230]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [231]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## NumPy Notes – Arithmetic and Math Functions

### * Array Arithmetic Operations

* Use `+`, `-`, `*`, `/` operators for element-wise operations  
* Works when arrays have the **same shape**  
* Example:
  * `a + b` → adds corresponding elements
  * `a * 2` → scalar multiplication, each element × 2

---

### * Broadcasting

* Allows operations between arrays of **different shapes**  
* Example:
  * `array1.shape = (1, 5)` and `array3.shape = (3, 5)`  
  * `array1 + array3` → `array1` is **broadcast** to each row of `array3`  
* Scalars also broadcast to all elements in an array  
  * `array3 + 5` adds 5 to each element

---

### * NumPy Functions

* `np.add(a, b)` → adds arrays element-wise (only 2 arguments allowed)  
* `np.subtract(a, b)` → subtracts element-wise  
* `np.multiply(a, b)` and `np.divide(a, b)` also available  

---

### * Sum and Cumulative Sum

* `np.sum(array)` → sum of all elements  
* `np.sum(array, axis=0)` → sum **down columns**  
* `np.sum(array, axis=1)` → sum **across rows**

* `np.cumsum(array)` → cumulative sum of flattened array  
* `np.cumsum(array, axis=0)` → cumulative sum **down columns**  
* `np.cumsum(array, axis=1)` → cumulative sum **across rows**

---

### * Mean, Max, and Min

* `array.mean()` → average of all elements  
* `np.mean(array, axis=0)` → column-wise average  
* `np.mean(array, axis=1)` → row-wise average

* `np.max(array, axis=1)` → max of each row  
* `np.min(array, axis=1)` → min of each row

---

### * Summary

* Use vectorized operations (`+`, `-`, `*`, `/`) for fast computation  
* Broadcasting enables flexible operations with different shapes  
* Built-in functions like `sum`, `mean`, `cumsum`, `max`, and `min` work with optional axis for direction  
* Scalar operations are broadcast to all array elements

In [232]:
import numpy as np

In [259]:
array_1 = np.array([[1,2,3,4,5]])

In [260]:
array_2 = np.array([1,2,3,4,5,6,7,8,8,9,9,10,1,3,4,6,8,8,10,20]).reshape(5,4)

In [261]:
array_3 = np.array([1,224,4,4,2,1,1,5,2,3,25,2,45,5,5,25,2,23,5,23,5,3,1,41,12]).reshape(5,5)

In [262]:
array_1

array([[1, 2, 3, 4, 5]])

In [263]:
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9,  9, 10],
       [ 1,  3,  4,  6],
       [ 8,  8, 10, 20]])

In [264]:
array_3

array([[  1, 224,   4,   4,   2],
       [  1,   1,   5,   2,   3],
       [ 25,   2,  45,   5,   5],
       [ 25,   2,  23,   5,  23],
       [  5,   3,   1,  41,  12]])

In [265]:
np.add(array_1,array_1)

array([[ 2,  4,  6,  8, 10]])

In [266]:
array_1+array_1

array([[ 2,  4,  6,  8, 10]])

In [267]:
array_1+array_1+array_1

array([[ 3,  6,  9, 12, 15]])

In [268]:
array_1.shape

(1, 5)

In [269]:
array_2.shape

(5, 4)

In [270]:
array_3.shape

(5, 5)

In [273]:
array_1+array_3

array([[  2, 226,   7,   8,   7],
       [  2,   3,   8,   6,   8],
       [ 26,   4,  48,   9,  10],
       [ 26,   4,  26,   9,  28],
       [  6,   5,   4,  45,  17]])

In [277]:
array_2_1 = array_2.T

In [278]:
array_1+array_2_1

array([[ 2,  7, 11,  5, 13],
       [ 3,  8, 12,  7, 13],
       [ 4,  9, 12,  8, 15],
       [ 5, 10, 13, 10, 25]])

In [279]:
array_3

array([[  1, 224,   4,   4,   2],
       [  1,   1,   5,   2,   3],
       [ 25,   2,  45,   5,   5],
       [ 25,   2,  23,   5,  23],
       [  5,   3,   1,  41,  12]])

In [280]:
array_3+10

array([[ 11, 234,  14,  14,  12],
       [ 11,  11,  15,  12,  13],
       [ 35,  12,  55,  15,  15],
       [ 35,  12,  33,  15,  33],
       [ 15,  13,  11,  51,  22]])

In [283]:
array_1-array_1

array([[0, 0, 0, 0, 0]])

In [284]:
array_1-array_2_1

array([[  0,  -3,  -5,   3,  -3],
       [ -1,  -4,  -6,   1,  -3],
       [ -2,  -5,  -6,   0,  -5],
       [ -3,  -6,  -7,  -2, -15]])

In [285]:
array_1-array_3

array([[   0, -222,   -1,    0,    3],
       [   0,    1,   -2,    2,    2],
       [ -24,    0,  -42,   -1,    0],
       [ -24,    0,  -20,   -1,  -18],
       [  -4,   -1,    2,  -37,   -7]])

In [289]:
np.subtract(array_1,array_3)

array([[   0, -222,   -1,    0,    3],
       [   0,    1,   -2,    2,    2],
       [ -24,    0,  -42,   -1,    0],
       [ -24,    0,  -20,   -1,  -18],
       [  -4,   -1,    2,  -37,   -7]])

In [290]:
array_1+20-5

array([[16, 17, 18, 19, 20]])

In [291]:
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9,  9, 10],
       [ 1,  3,  4,  6],
       [ 8,  8, 10, 20]])

In [292]:
array_2*4

array([[ 4,  8, 12, 16],
       [20, 24, 28, 32],
       [32, 36, 36, 40],
       [ 4, 12, 16, 24],
       [32, 32, 40, 80]])

In [293]:
array_3/2

array([[  0.5, 112. ,   2. ,   2. ,   1. ],
       [  0.5,   0.5,   2.5,   1. ,   1.5],
       [ 12.5,   1. ,  22.5,   2.5,   2.5],
       [ 12.5,   1. ,  11.5,   2.5,  11.5],
       [  2.5,   1.5,   0.5,  20.5,   6. ]])

In [295]:
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9,  9, 10],
       [ 1,  3,  4,  6],
       [ 8,  8, 10, 20]])

In [300]:
int(np.sum(array_2))

132

In [301]:
np.sum(array_2,axis=0)

array([23, 28, 33, 48])

In [302]:
np.sum(array_2,axis=1)

array([10, 26, 36, 14, 46])

In [303]:
np.cumsum(array_3)

array([  1, 225, 229, 233, 235, 236, 237, 242, 244, 247, 272, 274, 319,
       324, 329, 354, 356, 379, 384, 407, 412, 415, 416, 457, 469])

In [304]:
np.cumsum(array_3,axis=0)

array([[  1, 224,   4,   4,   2],
       [  2, 225,   9,   6,   5],
       [ 27, 227,  54,  11,  10],
       [ 52, 229,  77,  16,  33],
       [ 57, 232,  78,  57,  45]])

In [305]:
np.cumsum(array_3,axis=1)

array([[  1, 225, 229, 233, 235],
       [  1,   2,   7,   9,  12],
       [ 25,  27,  72,  77,  82],
       [ 25,  27,  50,  55,  78],
       [  5,   8,   9,  50,  62]])

In [306]:
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9,  9, 10],
       [ 1,  3,  4,  6],
       [ 8,  8, 10, 20]])

In [312]:
float(array_2.mean())

6.6

In [313]:
np.mean(array_2)

np.float64(6.6)

In [314]:
np.mean(array_2,axis=0)

array([4.6, 5.6, 6.6, 9.6])

In [315]:
np.mean(array_2,axis=1)

array([ 2.5,  6.5,  9. ,  3.5, 11.5])

In [317]:
int(np.amax(array_2))

20

In [321]:
np.amax(array_2,axis=0)

array([ 8,  9, 10, 20])

In [318]:
int(np.amin(array_2))

1

In [322]:
np.amin(array_2,axis=1)

array([1, 5, 8, 1, 8])

## NumPy Notes – Input and Output

### * Load data from `.txt` or `.csv` using `np.loadtxt()`

* Syntax:
  * `np.loadtxt('filename.txt', delimiter=',', skiprows=1, usecols=(1,))`
* Only works if all selected columns have the same data type
* If file is in same directory, use just the filename
* If file is in another location, use full file path
* `delimiter=','` for CSV files  
* `skiprows=1` to skip headers  
* `usecols=(1,)` selects only second column (indexing starts at 0)

---

### * Example: Load London bike data

```python
x = np.loadtxt('tfl-daily-cycle-hires.txt', delimiter=',', skiprows=1, usecols=(1,))
```

---

### * Common analysis after loading

* Count non-zero days: `np.count_nonzero(x)`
* Max value (most bikes hired): `np.max(x)`
* Min value (least bikes hired): `np.min(x)`
* Mean value (average): `np.mean(x)`
* Standard deviation: `np.std(x)`

---

### * Example output checks

```python
np.count_nonzero(x)   # Total non-zero values
np.max(x)             # Highest bikes hired in a day
np.mean(x)            # Average bikes per day
np.std(x)             # Spread of bike hires
```

---

### * Save array to file using `np.savetxt()`

* Syntax:
  * `np.savetxt('output.txt', x, delimiter=',')`
* Saves `x` to a text file in current directory
* Use full path if saving elsewhere

---

### * Summary Notes

* Use `np.loadtxt()` to read structured numeric data
* Use `delimiter`, `skiprows`, and `usecols` to customize load
* Use `np.savetxt()` to export processed arrays
* Pandas (covered next) is better for mixed/tabular data

In [323]:
import numpy as np

In [326]:
x = np.loadtxt('tfl-daily-cycle-hires.txt',delimiter=',',skiprows=1,usecols=1)

In [330]:
x

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [331]:
np.count_nonzero(x)

4081

In [332]:
x.max()

np.float64(73094.0)

In [333]:
x.min()

np.float64(2764.0)

In [334]:
x.mean()

np.float64(26261.932124479295)

In [335]:
x.std()

np.float64(9740.107235227775)

In [336]:
np.savetxt('test_output.txt',x)

In [337]:
x2 = np.loadtxt('test_output.txt')

In [338]:
x2

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])